# Generated by Django 4.1 on 2022-10-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='body',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='date_edited',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='public',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='user',
        ),
    ]
